apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:usuario-test-front
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec: 
  rules:
  - host: usuario-test.lumonidy.studio
    http:
      paths:
      - backend:
          service:
            name: usuario-test-front
            port:
              number: 80
        pathType: Prefix
        path: /
  tls:
  - hosts:
    - usuario-test.lumonidy.studio
    secretName: usuario-test-front-secret
