#golang-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: admin-front
spec:
  selector:
    app: admin-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP