#golang-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: usuario-front  
spec:
  selector: 
    app: usuario-front  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP